# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  dockercontainernetcore:
    image: dockercontainernetcore
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5094:5094
